# Generated by sila2.code_generator; sila2.__version__: 0.12.2

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.opentronsot2controller_impl import OpentronsOT2ControllerImpl
from .generated.opentronsot2controller import OpentronsOT2ControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        # TODO: fill in your server information
        if name is None:
            name = "OpentronsAdaptor"
        if description is None:
            description = "Mock implementation of opentrons OT-2 pipetting robot."
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="Adaptor",
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.opentronsot2controller = OpentronsOT2ControllerImpl(self)
        self.set_feature_implementation(OpentronsOT2ControllerFeature, self.opentronsot2controller)
