# Generated by sila2.code_generator; sila2.__version__: 0.12.2

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.cameracontroller_impl import CameraControllerImpl
from .generated.cameracontroller import CameraControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "CameraAdaptor"
        if description is None:
            description = "Captures image of pendant drop."
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="Adaptor",
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.cameracontroller = CameraControllerImpl(self)
        self.set_feature_implementation(CameraControllerFeature, self.cameracontroller)
