# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict
import time

from ..generated.opentronsot2controller import OpentronsOT2ControllerBase, PrepareDrop_Responses

if TYPE_CHECKING:
    from ..server import Server


class OpentronsOT2ControllerImpl(OpentronsOT2ControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def PrepareDrop(self, ExperimentPlanPath: str, *, metadata: MetadataDict) -> PrepareDrop_Responses:
        time.sleep(0.5)
        return PrepareDrop_Responses()
