# Generated by sila2.code_generator; sila2.__version__: 0.12.2

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.dataitemprovider_impl import DataItemProviderImpl
from .generated.dataitemprovider import DataItemProviderFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "DataService"
        if description is None:
            description = "Stores data items in collections and namespaces."
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="Service",
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.dataitemprovider = DataItemProviderImpl(self)
        self.set_feature_implementation(DataItemProviderFeature, self.dataitemprovider)
